name: Blob Hosting Storage CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "static/**"
      - "templates/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Templates Files
        run: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --destination '$web' --source ./templates --overwrite --auth-mode login

      - name: Upload Static Files
        run: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --destination '$web' --source ./static --overwrite --auth-mode login

      - name: Web URL
        run: |
          echo "Website available at: https://${{ secrets.STORAGE_ACCOUNT_NAME }}.z6.web.core.windows.net"

      - name: Deployment Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Deployment Successful
          to: mordecaiomindecloud@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Deployment Success

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.run_id }}
