name: Blob Hosting Storage CI/CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login To azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Teplates Files
        run: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --destination '$web' --source ./templates --overwrite

      - name: Upload Static files
        run: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --destination '$web'  --source ./static --overwrite

      - name: Getting Web URL
        run: |
          web_url=$(az storage account show --name ${{ secrets.STORAGE_ACCOUNT_NAME }} --query "primaryEndpoint.web" -o -tsv)

          echo "web available at $web_url"

      - name: Deployment Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Deployment Successful
          to: mordecai@gmail.com
          from: GitHub Actions
          body: |
            Deployment Success

            Repo: ${{ github.repository}}
            Branch: ${{ github.branch }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.run_id }}
